server:
  port: 8080


spring:
  application:
    name: ${project}

  datasource:
    name: masterDataSource
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: ${driverClass}
    tomcat:
      maxActive: 200
      initialSize: 5
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnReturn: false
      testOnBorrow: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
  file: ${project}.log

management:
  security:
    enabled: false


  